#!/usr/bin/env python3
"""Write paste-ready LaTeX tables from results/infer_bench/summary.json."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SUMMARY = ROOT / "results" / "infer_bench" / "summary.json"
OUT_DOCS = ROOT / "docs" / "reports" / "Infer_Bench_tables_only.tex"
OUT_RES = ROOT / "results" / "infer_bench" / "Infer_Bench_tables_only.tex"


def pct(x):
    return r"$%.1f\%%$" % (100.0 * x)


def main():
    s = json.loads(SUMMARY.read_text())
    by = {d["stem"]: d for d in s["datasets"]}
    h, q, p, t = by["halueval"], by["squad"], by["hotpotqa"], by["truthfulqa"]
    rf = s["online_rfperm"]
    hh = rf["hh_rlhf"]
    ha = rf["halueval"]

    lines = [
        r"% Infer-bench: four 300-example exports + existing OnlineRFPerm numbers.",
        r"% Requires booktabs. Generated by scripts/infer_bench/write_tex.py.",
        r"",
        r"\begin{table}[ht]",
        r"\centering",
        r"\caption{Infer-bench inventory. Local slices are $n=300$ head/mid/tail",
        r"windows of the named Hugging Face split. Venue cite keys are in the last column.}",
        r"\label{tab:infer-bench-inventory}",
        r"\small",
        r"\setlength{\tabcolsep}{3.5pt}",
        r"\begin{tabular}{@{}l l l r r l@{}}",
        r"\toprule",
        r"Dataset & Task & Hub split & Source $n$ & Export $n$ & Cite key \\",
        r"\midrule",
        r"HaluEval & Hallucination (QA) & \texttt{qa\_samples} & %d & 300 & \texttt{li-etal-2023-halueval} \\"
        % h["n_source_split"],
        r"SQuAD 1.1 & Extractive RC & validation & %d & 300 & \texttt{rajpurkar-etal-2016-squad} \\"
        % q["n_source_split"],
        r"HotpotQA & Multi-hop QA & distractor val. & %d & 300 & \texttt{yang-etal-2018-hotpotqa} \\"
        % p["n_source_split"],
        r"TruthfulQA & Truthfulness & generation val. & %d & 300 & \texttt{lin-etal-2022-truthfulqa} \\"
        % t["n_source_split"],
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        r"",
        r"\begin{table}[ht]",
        r"\centering",
        r"\caption{Characterization of the $n=300$ local JSONL exports.",
        r"SQuAD validation is article-grouped, so three windows cover few titles.}",
        r"\label{tab:infer-bench-slice}",
        r"\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{@{}l r r r l@{}}",
        r"\toprule",
        r"Dataset & Q words & Ans.\ words & Extra & Notes \\",
        r"\midrule",
        r"HaluEval & $%.1f$ & $%.1f$ & halluc.\ yes %s & knowledge $%.0f$ words \\"
        % (
            h["stats"]["question_words_mean"],
            h["stats"]["answer_words_mean"],
            pct(h["stats"]["hallucination_yes_rate"]),
            h["stats"]["knowledge_words_mean"],
        ),
        r"SQuAD & $%.1f$ & $%.1f$ & %d titles & context $%.0f$ words \\"
        % (
            q["stats"]["question_words_mean"],
            q["stats"]["answer_words_mean"],
            q["stats"]["n_titles"],
            q["stats"]["context_words_mean"],
        ),
        r"HotpotQA & $%.1f$ & $%.1f$ & bridge %d / cmp %d & all hard; $\approx 10$ paras \\"
        % (
            p["stats"]["question_words_mean"],
            p["stats"]["answer_words_mean"],
            p["stats"]["type_counts"]["bridge"],
            p["stats"]["type_counts"]["comparison"],
        ),
        r"TruthfulQA & $%.1f$ & $%.1f$ & adv.\ %d / non %d & %d categories \\"
        % (
            t["stats"]["question_words_mean"],
            t["stats"]["best_answer_words_mean"],
            t["stats"]["type_counts"]["Adversarial"],
            t["stats"]["type_counts"]["Non-Adversarial"],
            t["stats"]["n_categories"],
        ),
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        r"",
        r"\begin{table}[ht]",
        r"\centering",
        r"\caption{OnlineRFPerm landing results already shipped on the HF-prototype branch.",
        r"HaluEval uses a 2400-row \texttt{qa\_samples} stream (not the 300-export).",
        r"HH-RLHF is the alignment counterpart, not one of the four infer-bench exports.}",
        r"\label{tab:infer-bench-onlinerfperm}",
        r"\small",
        r"\setlength{\tabcolsep}{3.5pt}",
        r"\begin{tabular}{@{}l r r r r r r@{}}",
        r"\toprule",
        r"Stream & $n$ & Cut $t$ & Fire rate & First fire & Pre$\to$post & Ranking \\",
        r"\midrule",
        r"HaluEval QA & %d & $B_{%d}$ & $%.3f$ & $%d$ & halluc.\ $%.3f\to%.3f$ & AUROC $\texttt{po\_risk0}=%.2f$ \\"
        % (
            ha["n"],
            ha["cut_batch"],
            ha["fire_rate"],
            ha["first_fire_t"],
            ha["halluc_rate_before"],
            ha["halluc_rate_after"],
            ha["auroc_po_risk0_at_cut"],
        ),
        r"HH-RLHF helpful & %d & $B_{%d}$ & $%.3f$ & $%d$ & judge err $%.3f\to%.3f$ & style AUC $%.3f$ \\"
        % (
            hh["n"],
            4,
            hh["fire_rate"],
            hh["first_fire_t"],
            hh["judge_err_pre"],
            hh["judge_err_post"],
            hh["style_domain_auc"],
        ),
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        r"",
        r"\begin{table}[ht]",
        r"\centering",
        r"\caption{HaluEval OnlineRFPerm hop@cut vs.\ a quiet batch.",
        r"Gate $\gamma=1.25$. \texttt{po\_risk0} ranks audit candidates; it is not a fact checker.}",
        r"\label{tab:infer-bench-halu-hop}",
        r"\small",
        r"\begin{tabular}{@{}l c c c c@{}}",
        r"\toprule",
        r"Batch & Fired & Ratio & P@10 & Halluc.\ rate \\",
        r"\midrule",
        r"Quiet $t=2$ & no & $0.70$ & $0.70$ & $0.07$ \\",
        r"Cut $t=4$ & yes & $11.71$ & $1.00$ & $0.82$ \\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        r"",
    ]
    text = "\n".join(lines) + "\n"
    for out in (OUT_DOCS, OUT_RES):
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text)
        print("wrote", out)


if __name__ == "__main__":
    main()
