"""AGOD: Attribution-Guided Online adaptation controllers.

Reusable control-plane pieces for multimodal online LR routing:

- ``mmd``: unbiased RBF MMD² (covariate / P(X) sensor)
- ``shift``: concept vs covariate decomposition
- ``lr_controller``: Softmax α → per-modality LR multipliers (actuator)

Amazon smoke CLI: ``python3 scripts/run_agod_amazon_mmd_lr.py``
"""

from .adapter import (
    ADAPTER_LAYERS,
    GATE_POLICIES,
    AdapterConfig,
    AdapterDecision,
    DynamicGate,
    LayeredAdapter,
    alpha_entropy,
    characterize_gate_traj,
    characterize_soft_lr_traj,
    flops_rel_proj,
    n_star_for_lift,
    soft_lr_dispersion,
)
from .compute_ratio import (
    characterize_compute_ratio,
    modality_redundancy,
    predict_flops_from_correlation,
    predict_keep_set,
    unique_adapt_mass,
)
from .ensemble_decorr import (
    assign_ensemble_roles,
    characterize_ensemble_traj,
    gram_effective_rank,
    residual_uniqueness,
    role_lr_gains,
    soft_decorr_lr,
)
from .grad_corr_stat import (
    characterize_corr,
    characterize_stat_traj,
    correlation_from_pairs,
    effective_ensemble_size,
    fisher_z_test,
    gls_weights,
    partial_uniqueness,
    shrink_correlation,
    stat_corr_lr,
    temporal_gain,
    variance_stabilizing_scale,
)
from .lr_controller import (
    EMARouter,
    SCHEDULER_NAMES,
    aligned_cos_sim,
    alpha_to_lr,
    common_dim_grad_signature,
    cos_sim,
    damp_lr,
    equal_lr,
    flatten_grads,
    intensity_gain,
    modality_grad_cosine,
    schedule_modality_lr,
    soft_budget_lr,
    soft_cosine_lr,
    soft_entropy_lr,
    soft_gradcos_lr,
    soft_warmup_lr,
    softmax_scores,
    z_norm,
)
from .online_stacking import (
    METHODS as STACKING_METHODS,
    OnlineStacker,
    best_expert_loss,
    directional_scores,
    direction_match_weights,
    honest_step,
    leaky_step,
    linear_gain_is_vertex,
    mean_variance_pi,
    oracle_convex_combo,
    pi_to_lr,
    prequential_regret,
)
from .stack_logics import (
    LOGIC_NAMES,
    cauchy_step,
    entropy_regularized,
    eta_path,
    frank_wolfe_linear,
    mgda_min_norm,
    mixloss_weights,
    n_path,
    pseudo_bma_weights,
    quadratic_finite_step,
    rayleigh_gls,
    tau_path,
    taylor_remainder_scale,
)
from .stack_track import (
    RollingOSL,
    alignment_leak,
    disjoint_probe_holdout,
    kfold_oof_predict,
    oof_vs_leaky_stack,
    path_tv,
    run_switch_methods,
    sticky_mix,
    sticky_path,
    switch_delay,
    tv,
    tv_after_frac,
)
from .shift import decompose_hybrid, decompose_mmd, decompose_rf
from .mmd import rbf_mmd2, whiten_pair

__all__ = [
    "ADAPTER_LAYERS",
    "GATE_POLICIES",
    "AdapterConfig",
    "AdapterDecision",
    "DynamicGate",
    "LayeredAdapter",
    "characterize_gate_traj",
    "characterize_soft_lr_traj",
    "soft_lr_dispersion",
    "alpha_entropy",
    "n_star_for_lift",
    "flops_rel_proj",
    "rbf_mmd2",
    "whiten_pair",
    "decompose_mmd",
    "decompose_rf",
    "decompose_hybrid",
    "z_norm",
    "softmax_scores",
    "alpha_to_lr",
    "intensity_gain",
    "EMARouter",
    "SCHEDULER_NAMES",
    "schedule_modality_lr",
    "equal_lr",
    "soft_cosine_lr",
    "soft_budget_lr",
    "soft_warmup_lr",
    "damp_lr",
    "soft_entropy_lr",
    "soft_gradcos_lr",
    "cos_sim",
    "flatten_grads",
    "common_dim_grad_signature",
    "aligned_cos_sim",
    "modality_grad_cosine",
    "modality_redundancy",
    "unique_adapt_mass",
    "predict_keep_set",
    "predict_flops_from_correlation",
    "characterize_compute_ratio",
    "gram_effective_rank",
    "residual_uniqueness",
    "assign_ensemble_roles",
    "role_lr_gains",
    "soft_decorr_lr",
    "characterize_ensemble_traj",
    "correlation_from_pairs",
    "shrink_correlation",
    "effective_ensemble_size",
    "gls_weights",
    "partial_uniqueness",
    "fisher_z_test",
    "temporal_gain",
    "variance_stabilizing_scale",
    "characterize_corr",
    "stat_corr_lr",
    "characterize_stat_traj",
    "OnlineStacker",
    "STACKING_METHODS",
    "honest_step",
    "leaky_step",
    "oracle_convex_combo",
    "best_expert_loss",
    "prequential_regret",
    "pi_to_lr",
    "directional_scores",
    "direction_match_weights",
    "mean_variance_pi",
    "linear_gain_is_vertex",
    "LOGIC_NAMES",
    "quadratic_finite_step",
    "entropy_regularized",
    "mgda_min_norm",
    "mixloss_weights",
    "pseudo_bma_weights",
    "frank_wolfe_linear",
    "cauchy_step",
    "rayleigh_gls",
    "taylor_remainder_scale",
    "eta_path",
    "tau_path",
    "n_path",
    "RollingOSL",
    "tv",
    "path_tv",
    "tv_after_frac",
    "sticky_mix",
    "sticky_path",
    "switch_delay",
    "run_switch_methods",
    "oof_vs_leaky_stack",
    "kfold_oof_predict",
    "alignment_leak",
    "disjoint_probe_holdout",
]

__version__ = "0.1.0"
